services:
  llm:
    build:
      context: .
      dockerfile: Dockerfile
    image: llm:v1
    container_name: llm
    restart: always
    networks:
      - yt-mp3_default
    ports:
      - "1234:1234"
    tty: true
    stdin_open: true

networks:
  yt-mp3_default:
    external: true
