services:
  llm:
    build:
      context: .
      dockerfile: Dockerfile
    image: llm:v1
    container_name: llm
#    command: ["sleep","infinity"]
    ports:
      - "1234:1234"
    tty: true
    stdin_open: true
